version: "3.8"

services:
  ts-traefik:
    image: tailscale/tailscale:latest
    hostname: ${TS_HOSTNAME}
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_EXTRA_ARGS=--advertise-tags=${TS_ADVERTISE_TAGS}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - tailscale-data-traefik:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped
    ports:
      # using port 2096 for cloudflare https proxy
      - "2096:2096/tcp"
  traefik:
    image: traefik:v3.3
    command:
      - --log.level=INFO
      - --entryPoints.tcp2096.address=:2096/tcp
      # Dynamic: load from file provider
      - --providers.file.filename=/etc/traefik/dynamic/config.yml
      - --providers.file.watch=true
      - --accesslog=true
      - --accesslog.format=common
    configs:
      - source: traefik_dynamic
        target: /etc/traefik/dynamic/config.yml
        mode: 0444
    network_mode: service:ts-traefik
    depends_on:
      - ts-traefik
volumes:
  tailscale-data-traefik:
    driver: local


configs:
  traefik_dynamic:
    # noinspection HttpUrlsUsage
    content: |
      http:
        routers:
          tcp2096:
            entryPoints:
              - tcp2096
            rule: Host(`${DASHBOARD_HOST}`)
            service: tcp2096-svc
            middlewares:
              - dashboard-basic-auth

        services:
          tcp2096-svc:
            loadBalancer:
              servers:
                - url: "http://${TARGET_HOST}:${TARGET_PORT}"
      
        middlewares:
          dashboard-basic-auth:
            basicAuth:
              users:
                - "${DASHBOARD_USER}:${DASHBOARD_PASSWORD_HASH}"
